In [1]:
import numpy as np

In [2]:
image = np.array([
    [
        [255, 0, 0],      # Red
        [0, 255, 0],      # Green
        [0, 0, 255]       # Blue
    ],
    [
        [255, 255, 0],    # Yellow
        [255, 255, 255],  # White
        [0, 0, 0]         # Black
    ]
])

In [3]:
image.shape

(2, 3, 3)

In [6]:
image.ndim

3

There are 3 levels of [].

That's why this is a 3-dimensional NumPy array.

Dimension 1 → Row

Dimension 2 → Column

Dimension 3 → Value inside [255, 0, 0]

image[row, column, value]  to reach one individual number

(2,3,3)

2 → number of rows

3 → number of columns

3 → number of values in each element

Let's visualize the shape

Think of it as a table:

            Column 0       Column 1       Column 2


Row 0       [255,0,0]      [0,255,0]      [0,0,255]


Row 1       [255,255,0]    [255,255,255]  [0,0,0]

There are: 2 rows and 3 columns

And each cell contains:3 numbers

How to access elements?  image[row, column, position]

For a normal 2D array:  Important

array[row, column]

For your 3D array:

array[block, row, column]

For an RGB image, we'll eventually interpret the third position differently:

image[row, column, RGB_channel]

In [77]:
image

array([[[255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[255, 255,   0],
        [255, 255, 255],
        [  0,   0,   0]]])

In [7]:
#image[0] gives the block 0
image[0]

array([[255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255]])

In [8]:
#image[1] gives the 2nd  block
image[1]

array([[255, 255,   0],
       [255, 255, 255],
       [  0,   0,   0]])

image[0] → first block

image[1] → second block

In [10]:
image[0] # first block

array([[255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255]])

In [9]:
#image[0,0] block  0 and row 0 i.e first block and first row
image[0,0]

array([255,   0,   0])

In [11]:
#image[0,1] block 0 and row 2
image[0,1]

array([  0, 255,   0])

In [12]:
#image[0,1] block 0 and row 3
image[0,2]

array([  0,   0, 255])

image[0,0] → [255, 0, 0]

image[0,1] → [0, 255, 0]

image[0,2] → [0, 0, 255]

Notice something important:

image[0,0] gives 3 numbers, not one number.

Why?

Because we have only specified:

block + row

We haven't specified which of the 3 values we want.

Access one individual number

Now we need the third index.

image[block, row, column] to compare with numpy array 

image[row(block), column(row), position(column)] to compare in terms of RGB



image = np.array([

                 col 1              col2            col3  

    row--> 0 [[255, 0, 0],     [0, 255, 0],     [0, 0, 255]], --one 2d array

    row ->1 [[255, 255, 0],   [255, 255, 255],   [0, 0, 0]] --another 2d array
])

[255,   0,   0] is  one pixel and is considered as [R,G,B] i.e R = 255 , G = 0 and B = 0

inside pixel R index is 0 and G index is 1 and Blue index 2


3d array and consists of 2 two dimensional arrays

here col1 each pixel/element has 3 elements [255,0,0]

In [22]:
print(image[0,0,0]) # block 0 , row 0 , col 0
print(image[0,0,1]) # block 0 , row 0 , col 1
print(image[0,0,2]) # block 0 , row 0 , col 2


255
0
0


row    = 0
column = 0
value  = 0

image[0,0]     → [255, 0, 0]

image[0,0,0]   → 255

image[0,0,1]   → 0

image[0,0,2]   → 0

In [23]:
print(image[0,1,0]) # block 0 , row  1 , col 0
print(image[0,1,1]) # block 0 , row 1 , col 1
print(image[0,1,2]) # block 0 , row 1 , col 2

0
255
0


In [24]:
print(image[0,2,0]) # block 0 , row  2 , col 0
print(image[0,2,1]) # block 0 , row 2 , col 1
print(image[0,2,2]) # block 0 , row 2, col 2

0
0
255


In [25]:
print(image[1,0,0]) # block 1 , row 0 , col 0
print(image[1,0,1]) # block 1 , row 0 , col 1
print(image[1,0,2]) # block 1 , row 0 , col 2

255
255
0


In [26]:
print(image[1,1,0]) # block 1 , row 1 , col 0
print(image[1,1,1]) # block 1 , row 1 , col 1
print(image[1,1,2]) # block 1 , row 1 , poscolition 2

255
255
255


In [27]:
print(image[1,2,0]) # block 1 , row 2 , col 1
print(image[1,2,1]) # block 1 , row 2 , col 1
print(image[1,2,2]) # block 1 , row 2 , col
1

0
0
0


In [28]:
arr1d = np.array([1,2,3,4])

In [31]:
print(arr1d[0])
print(arr1d[1])

1
2


In [41]:
arr2d =  np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print(arr2d[0]) # row 1

[1 2 3]


In [43]:
print(arr2d[1])
print(arr2d[2])
print(arr2d[0,0])
print(arr2d[1,1])
print(arr2d[2,2])

[4 5 6]
[7 8 9]
1
5
9


In [49]:
arra3d = np.array([[[1,2,3],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]]])
print(arra3d.shape)
print(arra3d.ndim)
arra3d
# this is 3d array and consists of 2 two dimensional arrays of size 3 by 3


(2, 3, 3)
3


array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [50]:
arra3d = np.array([[[1,2,3],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]])
print(arra3d.shape)
print(arra3d.ndim)
arra3d

# this is 3d array and consists of 3 two dimensional arrays of size 3 by 3

(3, 3, 3)
3


array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
arra3d = np.array([[[1,2,3],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]],[[27,28,29],[30,31,32],[33,34,35]]])
print(arra3d.shape)
print(arra3d.ndim)
arra3d

# this is 3d array and consists of 4 two dimensional arrays of size 3 by 3

(4, 3, 3)
3


array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

# say shape is (2,3,2,2) then it is 4d array

# this is 4d array and consists of 3 two dimensional arrays of size 2 by 2

In [64]:
arr4d = np.array([[[1,2],[3,4]]])
print(arr4d.shape)
print(arr4d.ndim)
arr4d


(1, 2, 2)
3


array([[[1, 2],
        [3, 4]]])

In [66]:
arr4d = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(arr4d.shape)
print(arr4d.ndim)
arr4d


(2, 2, 2)
3


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [65]:
arr4d = np.array([[[[1,2],[3,4]]]])
print(arr4d.shape)
print(arr4d.ndim)
arr4d


(1, 1, 2, 2)
4


array([[[[1, 2],
         [3, 4]]]])

In [67]:
arr4d = np.array([[[[1,2],[3,4]],[[1,2],[3,4]]]])
print(arr4d.shape)
print(arr4d.ndim)
arr4d


(1, 2, 2, 2)
4


array([[[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]]])

In [78]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr3d.shape)
print(arr3d.ndim)
print(arr3d)

(2, 3, 3)
3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [74]:
print(arr3d[0])  # block 0

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
print(arr3d[1]) # block 1

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [81]:
print(arr3d[0,0]) # block 0 row 0

[1 2 3]


In [83]:
print(arr3d[0,0,0]) # block 0 row 0 col 0
print(arr3d[0,0,1]) # block 0 row 0 col 1
print(arr3d[0,0,2]) # block 0 row 0 col 2

1
2
3


In [84]:
print(arr3d[0,1,0]) # block 0 row 1 col 0
print(arr3d[0,1,1]) # block 0 row 1 col 1
print(arr3d[0,1,2]) # block 0 row 1 col 2

4
5
6


In [85]:
print(arr3d[1,0,0]) # block 1 row 0 col 0
print(arr3d[1,0,1]) # block 1 row 0 col 1
print(arr3d[1,0,2]) # block 1 row 0 col 2

10
11
12


In [86]:
print(arr3d[1,1,0]) # block 1 row 1 col 0
print(arr3d[1,1,1]) # block 1 row 1 col 1
print(arr3d[1,1,2]) # block 1 row 1 col 2

13
14
15


# just observe below for output commas

In [91]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [92]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [87]:
image = np.array([
    [
        [255, 0, 0],      # Red
        [0, 255, 0],      # Green
        [0, 0, 255]       # Blue
    ],
    [
        [255, 255, 0],    # Yellow
        [255, 255, 255],  # White
        [0, 0, 0]         # Black
    ]
])

In [88]:
image

array([[[255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[255, 255,   0],
        [255, 255, 255],
        [  0,   0,   0]]])

In [89]:
print(image)

[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [255 255 255]
  [  0   0   0]]]


Elements extractoin

In [93]:
image

array([[[255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[255, 255,   0],
        [255, 255, 255],
        [  0,   0,   0]]])


image = np.array([

                 col 1              col2            col3  

    row--> 0 [[255, 0, 0],     [0, 255, 0],     [0, 0, 255]], --one 2d array

    row ->1 [[255, 255, 0],   [255, 255, 255],   [0, 0, 0]] --another 2d array
])

[255,   0,   0] is  one pixel and is considered as [R,G,B] i.e R = 255 , G = 0 and B = 0

inside pixel R index is 0 and G index is 1 and Blue index 2

In [ ]:
image[:,:,0] # see above picture 

array([[255,   0,   0],
       [255, 255,   0]])

In [96]:
image[:,:,1]

array([[  0, 255,   0],
       [255, 255,   0]])

In [97]:
image[:,:,2]

array([[  0,   0, 255],
       [  0, 255,   0]])