 ### NUMPY
 
* library which we are using in dataanalytics | business analytics | datascience | generative ai | computer vision every where it is required 
* without numpy no datascience, da, gen ai 
* what is array --> collection of similar element 
* 1d array | 2d array | nd array 
* nd array - multidimension array
* data is of 2 parts
* structure data - excel sheet, csv 
* unstructure data - text, audio, vidieo, pdf, xml, sensor, conver to array 
				
what is numpy 
* numpy is a library which handle multidimension array 
* using numpy we can convert - (text - array | image - array | video - array ) 

## using help of numpy
* 1- arithmethic operatoon
* 2- statical operation 
* 3- bitwise operator
* 4- copy & view array
* 5- stacking 
* 6- matrix operation 
* 7- linear algebra 
* 8- broadcasting
* 9- math operation 
* 10- searching, sorting 

* array vs numpy 
* numpy -- 1d, 2d, nd 
* while you are working if you encouter then stop and listend class if you got error that you not working 
they learn who didnt practise regualar bais he got bugh 

In [3]:
import numpy as np

In [2]:
print(np.__version__)

2.5.2


In [3]:
import sys
sys.version

'3.14.3 (main, Feb  3 2026, 22:53:56) [MSC v.1944 64 bit (AMD64)]'

## Creating Arrays

In [ ]:
# Create List
my_list  = [0,1,2,3,4]
my_list

[0, 1, 2, 3, 4]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [8]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [30]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(
    start_or_stop,
    /,
    stop=None,
    step=1,
    *,
    dtype=None,
    device=None,
    like=None
)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When

* / means "positional-only"

* Everything before / must be passed by position.

* *means "keyword-only"

* Everything after * must be passed using its parameter name.

* stop and step are before *, so they can be supplied either positionally or by keyword:

* arange([start,] stop[, step,], dtype=None, *, like=None)
* inside [] is optional

In [9]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start_or_stop=10)  

TypeError: arange() got an unexpected keyword argument 'start_or_stop'

In [ ]:
np.arange(stop=10)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(start = 5,stop=10)  

array([5, 6, 7, 8, 9])

In [34]:
np.arange(start = 5,stop=10,step=2)  

array([5, 7, 9])

In [35]:
np.arange(stop=10,step=2)  

array([0, 2, 4, 6, 8])

In [36]:
np.arange(stop=10,2)  

SyntaxError: positional argument follows keyword argument (3200956370.py, line 1)

In [37]:
np.arange(10,step=2)  

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(10,2)  # Here 10 is treated as start and 2 as stop and  start < stop otherwise empty result

array([], dtype=int64)

In [41]:
np.arange(3)

array([0, 1, 2])

In [40]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(10,10)  # start < stop

array([], dtype=int64)

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [14]:
np.arange(10,30,3,3)

TypeError: Cannot interpret '3' as a data type

In [16]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,8)

array([], dtype=int64)

In [ ]:
np.arange(-20,8) # 1st arg < 2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [19]:
n =np.arange(-20,8) 
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [ ]:
np.zeros((2,2)) # nd array

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
n = np.zeros((5,9),dtype=int)
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
zero = np.zeros((2,2))
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
zero = np.zeros([2,2])  # here we passed as list instead tuple
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
range(5)

range(0, 5)

In [55]:
r = range(5)
r

range(0, 5)

In [56]:
for i in r:
    print(i)

0
1
2
3
4


In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
list(range(1,10,3))

[1, 4, 7]

In [60]:
rand(3,2)

NameError: name 'rand' is not defined

In [61]:
random.rand(3,2)

NameError: name 'random' is not defined

In [62]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [63]:
np.random.rand(4)

array([0.32973721, 0.68805599, 0.5670746 , 0.48875907])

In [64]:
np.random.rand(2,3)

array([[0.33002646, 0.69770714, 0.61625967],
       [0.27042422, 0.43425803, 0.39137264]])

In [ ]:
np.random.randint(2,10) # exclusive of 2nd arg

9

In [67]:
np.random.randint(5,20)

15

In [68]:
np.random.randint(0,1)

0

In [70]:
np.random.randint(10,30,5)

array([16, 16, 22, 10, 16], dtype=int32)

In [71]:
np.random.randint(10,30,5)

array([19, 16, 15, 24, 12], dtype=int32)

In [73]:
np.random.randint(1)

0

In [74]:
np.random.randint(30,20,3)

ValueError: low >= high

In [75]:
np.random.randint(-30,20,3)

array([  2, -21,   5], dtype=int32)

In [ ]:
np.random.randint(5,9)  #GET THE VALUE  >=5 and < 9

8

In [79]:
np.random.randint(1,20)

12

In [77]:
np.random.randint(1,20,(3,3))

array([[ 5, 17, 11],
       [ 3, 17,  8],
       [16,  9,  6]], dtype=int32)

In [80]:
np.random.rand(3)

array([0.93436147, 0.94110123, 0.92588415])

In [78]:
np.random.rand(3,3)

array([[0.70756881, 0.84041006, 0.04346506],
       [0.76787093, 0.15283145, 0.48745945],
       [0.20632085, 0.80599507, 0.26011132]])

In [81]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5).reshape(5,1)

ValueError: cannot reshape array of size 4 into shape (5,1)

### Indexing and slicing

In [83]:
np.arange(1,5).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [114]:
a = np.random.randint(10,20,(3,4))
a

array([[13, 13, 14, 18],
       [17, 13, 18, 17],
       [17, 14, 17, 13]], dtype=int32)

In [85]:
a[:]

array([[13, 13, 14, 12],
       [17, 19, 10, 11],
       [12, 13, 17, 11]], dtype=int32)

In [ ]:
a[1:3] # first 2 rows

array([[17, 19, 10, 11],
       [12, 13, 17, 11]], dtype=int32)

In [ ]:
a[1:3] # last 2 rows

array([[17, 19, 10, 11],
       [12, 13, 17, 11]], dtype=int32)

In [91]:
a[1,2]

np.int32(10)

In [92]:
print(a[1,2])

10


In [94]:
print(a[2,0])

12


In [ ]:
print(a[1,-1])  # 2nd row last element

11


In [96]:
a[0:]

array([[13, 13, 14, 12],
       [17, 19, 10, 11],
       [12, 13, 17, 11]], dtype=int32)

In [ ]:
# start = 0 and stop = -1 and is excluded. a has 3 rows :
# +index 0, 1, 2 and
# -index -3,-2,-1
a[0:-1] # so it will print from 0 to -2  i.e 0 to 1

array([[13, 13, 14, 12],
       [17, 19, 10, 11]], dtype=int32)

In [ ]:
a[0:-2] #   0 to -3(i.e 0)  0 to 0

array([[13, 13, 14, 12]], dtype=int32)

In [ ]:
a[0:-3] # here -3 is same as 0 and -3 is excluded so it is  0 to 0 and 0 is excluded so empty array

array([], shape=(0, 4), dtype=int32)

In [115]:
a

array([[13, 13, 14, 18],
       [17, 13, 18, 17],
       [17, 14, 17, 13]], dtype=int32)

In [116]:
print(a[-3,3])
print(a[0,3])
print(a[2,-1])
print(a[-1,-1])

18
18
13
13


In [117]:
a

array([[13, 13, 14, 18],
       [17, 13, 18, 17],
       [17, 14, 17, 13]], dtype=int32)

In [ ]:
a[::-1] # row wize reverse

array([[17, 14, 17, 13],
       [17, 13, 18, 17],
       [13, 13, 14, 18]], dtype=int32)

In [119]:
a[::-2]

array([[17, 14, 17, 13],
       [13, 13, 14, 18]], dtype=int32)

In [121]:
b = np.random.randint(10,40,(6,6))
b

array([[14, 25, 30, 26, 27, 21],
       [23, 29, 36, 33, 19, 13],
       [32, 21, 38, 33, 34, 21],
       [13, 33, 10, 10, 10, 29],
       [33, 32, 23, 29, 20, 33],
       [14, 24, 35, 13, 24, 20]], dtype=int32)

In [ ]:
b[::-2] # in last row to first row with step size 2

array([[14, 24, 35, 13, 24, 20],
       [13, 33, 10, 10, 10, 29],
       [23, 29, 36, 33, 19, 13]], dtype=int32)

## Operations

In [144]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
id(c)

1678408742064

In [146]:
print(c.min())

1


In [147]:
print(c.max())

9


In [148]:
print(c.mean())

5.0


In [149]:
print(c.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [152]:
print(c.mode())

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [154]:
row = c[:1]
row

array([[1, 2, 3]])

In [157]:
print(row.min())
print(row.max())
print(row.mean())


1
3
2.0


In [158]:
print(row.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [167]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [168]:
d = np.array([1,2,3,4,5,6])
d

array([1, 2, 3, 4, 5, 6])

In [170]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [172]:
d.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [173]:
d.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [174]:
d.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [178]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
d.reshape(2,3,order = 'C')

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d.reshape(2,3,order = 'F') # print element with fortran 

array([[1, 3, 5],
       [2, 4, 6]])

In [183]:
d.reshape(2,3,order = 'A') # A almost give you c type output 

array([[1, 2, 3],
       [4, 5, 6]])

### Indexing and slicing

In [15]:
mat = np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Basic indexing
* mat[row, col]

In [16]:
print(mat[0,0]) # First row and first col

0


In [17]:
print(mat[0,1]) # First row and 2nd col

1


In [ ]:
print(mat[4,4]) # last row and last col

24


### Negative indexing

In [20]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
print(mat[-1,-1]) # last row and last col

24


In [24]:
print(mat[-2,-5]) # last 2nd row and first col

15


In [ ]:
print(mat[-5,-1]) # first row and last col

4


In [ ]:
print(mat[-3,-3])  # 12

12


In [ ]:
print(mat[-1,0]) #last row and first col

20


In [ ]:
print(mat[-5,0]) # first row and first col

0


### Selecting an entire row

In [29]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
print(mat[4])  # last row

[20 21 22 23 24]


In [ ]:
print(mat[-1]) # last row

In [ ]:
print(mat[0]) # first row

[0 1 2 3 4]


In [ ]:
print(mat[0,:]) # first row . is same as mat[0]  . here : means all columns

[0 1 2 3 4]


In [32]:
print(mat[-5]) # first row

[0 1 2 3 4]


In [34]:
print(mat[-5,:]) # first row  is same as mat[-5]

[0 1 2 3 4]


### Selecting an entire column

In [35]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
mat[:,0]  # first col

array([ 0,  5, 10, 15, 20])

In [37]:
mat[:,-1] # last col

array([ 4,  9, 14, 19, 24])

In [ ]:
mat[:,1] # 2nd column

array([ 1,  6, 11, 16, 21])

In [ ]:
mat[:,:] # all rows and all cols

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [188]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [189]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [191]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [40]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Row slicing

In [ ]:
mat[0:2] # first 2 rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
mat[0:2,:] # first 2 rows same as above

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
mat[-1:] # last row

array([[20, 21, 22, 23, 24]])

In [44]:
mat[-1:,:] # last row

array([[20, 21, 22, 23, 24]])

In [45]:
mat[-2:] # last 2 rows

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
mat[-2:,:] # last 2 rows

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
mat[1:3] # 2nd row to 3rd row

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
mat[1:3,:] # 2nd row to 3rd row same as above

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
mat[0:-1] # except last row

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
mat[0:-1,:] # except last row same as above

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Slicing rows AND columns

In [52]:
mat[2:6,2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [53]:
mat[2:6,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [54]:
mat[2:6,3:6]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [55]:
mat


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
mat[::-1] # reverse rows

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [57]:
mat[::-1,:] # reverse rows same as above

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [58]:
mat[:,::-1] # reverse cols

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

In [59]:
mat[::-1,::-1] # reverse row and cols

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [60]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
mat[0:5:2] # rows with step 2

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [62]:
mat[0:5:2,0:5:2] # both rows and cols with step 2

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [ ]:
mat[0:5:2,0:5:3] # both rows step 2 and col step 3

array([[ 0,  3],
       [10, 13],
       [20, 23]])

In [4]:
m = np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
m[0] # print first row

array([1, 2, 3, 4, 5])

In [ ]:
print(m[0][1]) # first row 2nd col

2


In [199]:
m[1] # print 2nd row

array([ 6,  7,  8,  9, 10])

In [200]:
m[-1] # print last row

array([21, 22, 23, 24, 25])

In [201]:
m[-2] # print last 2nd row

array([16, 17, 18, 19, 20])

In [203]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [204]:
m[:,0] # print 1st column

array([ 1,  6, 11, 16, 21])

In [202]:
m[:,1] # print 2nd column

array([ 2,  7, 12, 17, 22])

In [205]:
m[:,-1] # print last column

array([ 5, 10, 15, 20, 25])

In [206]:
m[:,-2] # print last 2nd column

array([ 4,  9, 14, 19, 24])

In [207]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
print(m[0,4]) # 1st row last 

5


In [210]:
print(m[0,-1]) # 1st row last

5


In [212]:
print(m[4,4]) # last row last 

25


In [213]:
print(m[-1,-1]) # last row last 

25


In [214]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [218]:
print(m[4,0]) # 1st last

21


In [222]:
print(m[3,3]) # 4th row 4th 

19


In [224]:
print(m[-1,-1]) # last row last col

25


In [225]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
m[:,1] # 2nd col

array([ 2,  7, 12, 17, 22])

In [ ]:
m[:,-1] # last col

array([ 5, 10, 15, 20, 25])

In [ ]:
m[:1,] # 1sr row

array([[1, 2, 3, 4, 5]])

In [230]:
m[:2,]# 1st 2 rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
m[-1,] #last row

array([21, 22, 23, 24, 25])

In [ ]:
m[-2:,] # last 2 rows

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [234]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
m[:,0] # 1st col  # slice before comma goes for rows and after comma goes for columns

array([ 1,  6, 11, 16, 21])

In [236]:
m[:,1] # 2nd col

array([ 2,  7, 12, 17, 22])

In [237]:
m[:,-1] # last col

array([ 5, 10, 15, 20, 25])

In [ ]:
m[:,-2:-1] # last 2nd col

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [240]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [241]:
m[0:2,0:2] # first 2 by 2 

array([[1, 2],
       [6, 7]])

In [245]:
m[0:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [246]:
m[3:,0:2]

array([[16, 17],
       [21, 22]])

In [ ]:
m[3:,3:]  # slice before comma goes for rows and after comma goes for columns

array([[19, 20],
       [24, 25]])

In [248]:
m


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
m[2:4,2:4]  # 2:4 for rows and 2nd 2:4 for columns

array([[13, 14],
       [18, 19]])

### Masking of filter

In [250]:
m[m<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
m[m>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
m > 20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [253]:
m[m==23]

array([23])

In [254]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [283]:
import random
def generate_otp(length):
    """Generate otp of given length"""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp
# Example usage with length 4
otp_length = 4
otp = generate_otp(otp_length)
print(f"Your OTP is {otp}")

Your OTP is 4234


In [64]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [65]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [66]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


### Mathematical Functions

In [ ]:
a = np.array([1,2,3,4])
print(np.add(a,2)) # add 2 to every element

[3 4 5 6]


In [68]:
a = np.array([1,2,3,4])
print(np.power(a,2))

[ 1  4  9 16]


In [69]:
a = np.array([1,2,3,4])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [70]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


### Statistical Functions

In [72]:
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.min(a))
print(np.max(a))

3.0
1
5


### Boolean & Logical Functions

In [73]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [74]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [75]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


### Array Attributes

In [76]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


### Other Functions

In [77]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [78]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [79]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
